--[[==========================================================================
  Atmosphere — simulation scenarios

  A dealer must be able to test programming without waiting for weather
  (spec: mandatory). Each scenario yields a synthetic normalized observation
  and/or CAP alert set that is fed into THE SAME engine.step() path as live
  data — the only difference is the simulation flag riding the snapshot.

  Alert scenarios go through walerts.normalize like real CAP payloads, so a
  simulated Tornado Warning exercises classification, admission filters,
  reconcile, and event mapping identically to a real one.
============================================================================]]

local walerts = require("atmosphere.alerts")

local M = {}

local function obs(now, over)
  local o = {
    timestamp = now,
    station = "SIMULATED",
    textDescription = "Simulated",
    tempC = 21,
    tempF = 70,
    feelsLikeF = 70,
    feelsLikeC = 21,
    humidity = 45,
    windMph = 5,
    gustMph = nil,
    windDeg = 180,
    windCompass = "S",
    pressureInHg = 29.92,
    pressurePa = 101325,
    visibilityMi = 10,
    visibilityM = 16093,
    cloudCover = 5,
    flags = { rain = false, snow = false, thunder = false, fog = false, ice = false, clear = true, cloudy = false },
  }
  for k, v in pairs(over or {}) do
    o[k] = v
  end
  return o
end

local function capAlert(now, event, severity, over)
  local raw = {
    id = "urn:oid:simulated." .. event:gsub("%W", "-"):lower(),
    event = event,
    headline = "SIMULATED: " .. event,
    severity = severity,
    certainty = "Observed",
    urgency = "Immediate",
    status = "Actual",
    messageType = "Alert",
    sent = now,
    senderName = "Atmosphere Simulator",
    areaDesc = "This property (simulated)",
    description = "This is a simulated " .. event .. " generated by SmartBuildOS Atmosphere for programming tests.",
    instruction = "No action required. This is a simulation.",
    response = "None",
  }
  for k, v in pairs(over or {}) do
    raw[k] = v
  end
  local a = walerts.normalize(raw)
  -- Times as epochs, filled directly (normalize parses strings; simulation
  -- supplies epochs so scenarios need no date formatting).
  a.effective = now
  a.onset = now
  a.expires = now + 2 * 3600
  a.ends = now + 2 * 3600
  return a
end

--- Scenario table: key -> function(now) -> { obs = ..., alerts = {...} }.
--- An absent obs means "keep current conditions, add the alerts".
M.SCENARIOS = {
  clear = function(now)
    return { obs = obs(now, {}), alerts = {} }
  end,
  cloudy = function(now)
    return {
      obs = obs(now, { textDescription = "Overcast", cloudCover = 95, flags = { cloudy = true } }),
      alerts = {},
    }
  end,
  rain = function(now)
    return {
      obs = obs(now, { textDescription = "Rain", cloudCover = 90, humidity = 88, flags = { rain = true } }),
      alerts = {},
    }
  end,
  heavy_rain = function(now)
    return {
      obs = obs(now, {
        textDescription = "Heavy Rain",
        cloudCover = 100,
        humidity = 95,
        visibilityMi = 1.5,
        windMph = 18,
        flags = { rain = true },
      }),
      alerts = {},
    }
  end,
  thunderstorm = function(now)
    return {
      obs = obs(now, {
        textDescription = "Thunderstorm",
        cloudCover = 100,
        windMph = 22,
        gustMph = 38,
        flags = { rain = true, thunder = true },
      }),
      alerts = {},
    }
  end,
  high_wind = function(now)
    return { obs = obs(now, { textDescription = "Windy", windMph = 28, gustMph = 40 }), alerts = {} }
  end,
  dangerous_wind = function(now)
    return { obs = obs(now, { textDescription = "Damaging Winds", windMph = 45, gustMph = 60 }), alerts = {} }
  end,
  freeze = function(now)
    return {
      obs = obs(now, { textDescription = "Clear and Cold", tempF = 28, tempC = -2.2, feelsLikeF = 22 }),
      alerts = {},
    }
  end,
  extreme_heat = function(now)
    return {
      obs = obs(now, { textDescription = "Hot", tempF = 101, tempC = 38.3, feelsLikeF = 108, humidity = 60 }),
      alerts = {},
    }
  end,
  snow = function(now)
    return {
      obs = obs(now, {
        textDescription = "Snow",
        tempF = 30,
        tempC = -1.1,
        cloudCover = 100,
        visibilityMi = 0.8,
        flags = { snow = true },
      }),
      alerts = {},
    }
  end,
  fog = function(now)
    return {
      obs = obs(now, { textDescription = "Fog", visibilityMi = 0.3, cloudCover = 100, flags = { fog = true } }),
      alerts = {},
    }
  end,
  tornado_watch = function(now)
    return { alerts = { capAlert(now, "Tornado Watch", "Severe") } }
  end,
  tornado_warning = function(now)
    return {
      obs = obs(now, {
        textDescription = "Thunderstorm",
        windMph = 35,
        gustMph = 60,
        cloudCover = 100,
        flags = { rain = true, thunder = true },
      }),
      alerts = { capAlert(now, "Tornado Warning", "Extreme") },
    }
  end,
  severe_thunderstorm_warning = function(now)
    return {
      obs = obs(now, {
        textDescription = "Thunderstorm",
        windMph = 30,
        gustMph = 55,
        flags = { rain = true, thunder = true },
      }),
      alerts = { capAlert(now, "Severe Thunderstorm Warning", "Severe") },
    }
  end,
  flood_warning = function(now)
    return {
      obs = obs(now, { textDescription = "Heavy Rain", humidity = 98, flags = { rain = true } }),
      alerts = { capAlert(now, "Flood Warning", "Severe") },
    }
  end,
  hurricane_warning = function(now)
    return {
      obs = obs(now, {
        textDescription = "Tropical Storm Conditions",
        windMph = 65,
        gustMph = 90,
        pressureInHg = 28.5,
        flags = { rain = true },
      }),
      alerts = { capAlert(now, "Hurricane Warning", "Extreme") },
    }
  end,
}

--- Ordered scenario names for property lists / UI menus.
M.NAMES = {
  "clear",
  "cloudy",
  "rain",
  "heavy_rain",
  "thunderstorm",
  "high_wind",
  "dangerous_wind",
  "freeze",
  "extreme_heat",
  "snow",
  "fog",
  "tornado_watch",
  "tornado_warning",
  "severe_thunderstorm_warning",
  "flood_warning",
  "hurricane_warning",
}

--- Builds a scenario. Returns { obs?, alerts = {...} } or nil for unknown.
function M.build(name, now)
  local f = M.SCENARIOS[tostring(name or ""):lower():gsub(" ", "_")]
  if f == nil then
    return nil
  end
  return f(now)
end

return M
